#!/usr/bin/env node
// Build the canonical KB into two deliverables:
//   dist/kb/articles/*.md   — one file per topic, frontmatter stripped, ready
//                             to upload individually to GHL Conversation AI
//   dist/kb/bundle.md       — every article concatenated with a TOC, ready
//                             to upload as a single document to GHL Ask AI /
//                             AI Agent Studio
//   dist/kb/manifest.json   — index of every article with metadata, useful
//                             if/when we automate the GHL upload via API

import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "docs/kb");
const OUT = path.join(ROOT, "dist/kb");

// Anything in this list will fail the build if found anywhere in the KB.
// These are our whitelabel tech partners — they must never surface in
// customer-facing AI answers.
const FORBIDDEN_PATTERNS = [
  /\bprop\s*account\b/i,
  /\bpropaccount\b/i,
  /\bfpfx\b/i,
  /\bgooeytrader\b/i,
];

function parseFrontmatter(raw) {
  if (!raw.startsWith("---\n")) {
    return { meta: {}, body: raw };
  }
  const end = raw.indexOf("\n---", 4);
  if (end === -1) return { meta: {}, body: raw };
  const fm = raw.slice(4, end);
  const body = raw.slice(end + 4).replace(/^\n+/, "");
  const meta = {};
  for (const line of fm.split("\n")) {
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!m) continue;
    let value = m[2].trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      value = value
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    }
    meta[m[1]] = value;
  }
  return { meta, body };
}

async function walkMarkdown(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await walkMarkdown(full, out);
    } else if (entry.name.endsWith(".md") && entry.name !== "README.md") {
      out.push(full);
    }
  }
  return out;
}

function slugify(filePath) {
  // docs/kb/04-rules/daily-loss-limit.md -> 04-rules__daily-loss-limit
  const rel = path.relative(SRC, filePath).replace(/\.md$/, "");
  return rel.replace(/\//g, "__");
}

async function main() {
  if (!existsSync(SRC)) {
    console.error(`KB source not found at ${SRC}`);
    process.exit(1);
  }

  if (existsSync(OUT)) await rm(OUT, { recursive: true, force: true });
  await mkdir(path.join(OUT, "articles"), { recursive: true });

  const files = (await walkMarkdown(SRC)).sort();
  const articles = [];
  const violations = [];

  for (const file of files) {
    const raw = await readFile(file, "utf8");
    const { meta, body } = parseFrontmatter(raw);

    for (const pattern of FORBIDDEN_PATTERNS) {
      if (pattern.test(raw)) {
        violations.push({ file: path.relative(ROOT, file), pattern: pattern.source });
      }
    }

    const slug = slugify(file);
    const title = meta.title || slug;
    const heading = `# ${title}\n\n`;
    const articleOut = heading + body.trim() + "\n";

    await writeFile(path.join(OUT, "articles", `${slug}.md`), articleOut);
    articles.push({ slug, file: path.relative(ROOT, file), meta, body: body.trim() });
  }

  if (violations.length) {
    console.error("\n❌ Forbidden partner-name mentions found:");
    for (const v of violations) console.error(`   ${v.file}  (matched ${v.pattern})`);
    console.error("\nRemove these references before building. Build aborted.\n");
    process.exit(1);
  }

  // Bundle with TOC
  const toc = articles
    .map((a, i) => `${i + 1}. **${a.meta.title || a.slug}** — \`${a.file}\``)
    .join("\n");

  const bundleSections = articles
    .map((a) => `## ${a.meta.title || a.slug}\n\n_Source: \`${a.file}\`_\n\n${a.body}`)
    .join("\n\n---\n\n");

  const bundle = [
    "# Hybrid Funding — Canonical Knowledge Base (Bundle)",
    "",
    `_Generated ${new Date().toISOString()} from \`docs/kb/\`. Do not edit this file directly — edit the source markdown and re-run \`npm run build:kb\`._`,
    "",
    "## Table of Contents",
    "",
    toc,
    "",
    "---",
    "",
    bundleSections,
    "",
  ].join("\n");

  await writeFile(path.join(OUT, "bundle.md"), bundle);

  const manifest = {
    generated_at: new Date().toISOString(),
    article_count: articles.length,
    articles: articles.map((a) => ({
      slug: a.slug,
      source: a.file,
      title: a.meta.title,
      category: a.meta.category,
      tags: a.meta.tags,
      applies_to: a.meta.applies_to,
      last_updated: a.meta.last_updated,
    })),
  };
  await writeFile(path.join(OUT, "manifest.json"), JSON.stringify(manifest, null, 2));

  console.log(`\n✓ Built ${articles.length} articles`);
  console.log(`  → ${path.relative(ROOT, path.join(OUT, "articles"))}/*.md`);
  console.log(`  → ${path.relative(ROOT, path.join(OUT, "bundle.md"))}`);
  console.log(`  → ${path.relative(ROOT, path.join(OUT, "manifest.json"))}`);
  console.log();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
